services:
  - type: web
    name: mdata-api-python
    env: docker
    dockerfilePath: ./parsers/python/Dockerfile
    dockerContext: ./parsers/python
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: mdata-api-typescript
    env: docker
    dockerfilePath: ./parsers/typescript/Dockerfile
    dockerContext: ./parsers/typescript
    plan: free
    envVars:
      - key: PORT
        value: 3000